/**
 * Central route config: which paths exist and are implemented.
 * Use this to avoid linking to non-existent routes (404s).
 * Add paths here when you create the corresponding page.
 */
export const ROUTES = {
  login: '/login',
  signup: '/signup',
  verify: '/verify',
  splash: '/splash',
  dashboard: '/dashboard',
  profile: '/profile',
  account: '/account',
  help: '/help',
  privacy: '/privacy',
  terms: '/terms',
  comingSoon: '/coming-soon',
  profileEdit: '/profile/edit',
  groups: '/groups',
  paymentHistory: '/payment-history',
  refer: '/refer',
  locations: '/locations',
  notifications: '/notifications',
  availability: '/availability',
  activities: '/activities',
  sessions: '/sessions',
  trainers: '/trainers',
  sessionDetail: (id: string) => `/sessions/${id}`,
  activityDetail: (id: string) => `/activities/${id}`,
  trainerDetail: (id: string) => `/trainers/${id}`,
  activityArea: '/activity-area',
  myActivities: '/my-activities',
  certificates: '/certificates',
  bankDetails: '/bank-details',
  reviews: '/reviews',
  earning: '/earning',

  adminDashboard: '/admin/dashboard',
  adminMasterData: '/admin/master-data',
  adminActivity: '/admin/activity',
  adminFaq: '/admin/faq',
  adminContactUs: '/admin/contact',
  adminCustomizeDashboard: '/admin/customize-dashboard',
  adminDiscount: '/admin/discount',
  adminDiscountDetail: (id: string) => `/admin/discount/${id}`,
  adminTrainers: '/admin/trainers',
  adminTrainerDetail: (id: string) => `/admin/trainers/${id}`,
  adminCustomers: '/admin/customers',
  adminCustomerDetail: (id: string) => `/admin/customers/${id}`,
  adminSessions: '/admin/sessions',
  adminSessionDetail: (id: string) => `/admin/sessions/${id}`,
  adminEarning: '/admin/earning',
  adminSupport: '/admin/support',
  adminSupportDetail: (id: string) => `/admin/support/${id}`,
  adminUsers: '/admin/users',
  adminUserDetail: (id: string) => `/admin/users/${id}`,
  adminUserRoles: '/admin/user-roles',
} as const;

/** Paths that have a real page (no 404). Use for <Link href={}> only when true. */
export const IMPLEMENTED = new Set<string>([
  ROUTES.login,
  ROUTES.signup,
  ROUTES.verify,
  ROUTES.splash,
  ROUTES.dashboard,
  ROUTES.profile,
  ROUTES.account,
  ROUTES.help,
  ROUTES.privacy,
  ROUTES.terms,
  ROUTES.comingSoon,
  ROUTES.profileEdit,
  ROUTES.groups,
  ROUTES.paymentHistory,
  ROUTES.refer,
  ROUTES.locations,
  ROUTES.notifications,
  ROUTES.availability,
  ROUTES.activities,
  ROUTES.sessions,
  ROUTES.trainers,
  ROUTES.activityArea,
  ROUTES.myActivities,
  ROUTES.certificates,
  ROUTES.bankDetails,
  ROUTES.reviews,
  ROUTES.earning,

  ROUTES.adminDashboard,
  ROUTES.adminMasterData,
  ROUTES.adminActivity,
  ROUTES.adminFaq,
  ROUTES.adminContactUs,
  ROUTES.adminCustomizeDashboard,
  ROUTES.adminDiscount,
  ROUTES.adminTrainers,
  ROUTES.adminCustomers,
  ROUTES.adminSessions,
  ROUTES.adminEarning,
  ROUTES.adminSupport,
  ROUTES.adminUsers,
  ROUTES.adminUserRoles,
]);

/** Use for profile/nav: link to path if implemented, else to placeholder. */
export function getProfileLink(path: string): string {
  return IMPLEMENTED.has(path) ? path : '/coming-soon';
}
